minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
        language_version: python3
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        language_version: python3
      - id: mixed-line-ending
        args: [--fix=lf]
        language_version: python3
      - id: end-of-file-fixer
        language_version: python3
      - id: check-ast
        language_version: python3
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
      - id: insert-license
        language: python
        files: ^(feed|tests)\/(?!.*__init__\.py).+\.py$
        args: [--license-filepath, "LICENSE_header"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--count, "--select=E9,F63,F7,F82", --show-source, --statistics]

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: [--profile, black]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        args: [--namespace-packages, --ignore-missing-imports]
