# https://medium.com/google-cloud/deploy-to-cloud-run-using-gitlab-ci-e056685b8eeb
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', '${_GITLAB_REGISTRY_IMAGE}:${_GIT_COMMIT_SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_GITLAB_REGISTRY_IMAGE}:${_GIT_COMMIT_SHORT_SHA}', 'gcr.io/$PROJECT_ID/wyin-be-feed:${_GIT_COMMIT_SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_GITLAB_REGISTRY_IMAGE}:${_GIT_COMMIT_SHORT_SHA}', 'gcr.io/$PROJECT_ID/wyin-be-feed']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wyin-be-feed:${_GIT_COMMIT_SHORT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wyin-be-feed']

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'wyin-be-feed',
      '--image', 'gcr.io/$PROJECT_ID/wyin-be-feed:${_GIT_COMMIT_SHORT_SHA}',
      '--region', 'europe-west4', # https://cloud.google.com/compute/docs/regions-zones#available
      '--platform', 'managed',
      '--concurrency', '80',
      '--cpu', '1',
      '--memory', '128Mi',
      '--min-instances', '0',
      '--max-instances', '4', # "instances of 3 or less might experience unexpected downtime"
      '--timeout', '30s',
      '--allow-unauthenticated'
    ]
options:
    logging: CLOUD_LOGGING_ONLY
