# https://medium.com/google-cloud/deploy-to-cloud-run-using-gitlab-ci-e056685b8eeb
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'BUILD_VERSION=${_API_VERSION}', '--pull', '-t', 'gcr.io/$PROJECT_ID/wyin-be-feed', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wyin-be-feed']

  - name: "gcr.io/cloud-builders/gcloud"
    args: [
      'run',
      'deploy',
      'wyin-be-feed',
      '--image', 'gcr.io/$PROJECT_ID/wyin-be-feed',
      '--region', 'europe-west4', # https://cloud.google.com/compute/docs/regions-zones#available
      '--platform', 'managed',
      '--concurrency', '80',
      '--cpu', '1',
      '--memory', '128Mi',
      '--min-instances', '0',
      '--max-instances', '1', # "instances of 3 or less might experience unexpected downtime"
      '--timeout', '30s',
      '--allow-unauthenticated'
    ]
options:
    logging: CLOUD_LOGGING_ONLY
